import type { Metadata } from "next";
import { ThemeProvider } from "@/components/theme-provider";
import TopNav from "@/components/nav/top-nav";
import { AuthProvider } from "@/context/auth";

import { Comic_Neue as ComicNeue } from "next/font/google";

// Import Comic Neue
const comic = ComicNeue({ subsets: ["latin"], weight: "400" });

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* analytics */}
        <script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-RYED8LHQK5"
        ></script>
        <script
          dangerouslySetInnerHTML={{
            __html: `
                window.dataLayer = window.dataLayer || [];
                function gtag(){dataLayer.push(arguments);}
                gtag('js', new Date());

                gtag('config', 'G-RYED8LHQK5');
              `,
          }}
        />
        {/* ad */}
        <script
          async
          src="https://www.googletagmanager.com/gtag/js?id=AW-374328102"
        ></script>
        <script
          dangerouslySetInnerHTML={{
            __html: `
                window.dataLayer = window.dataLayer || [];
                function gtag(){dataLayer.push(arguments);}
                gtag('js', new Date());

                gtag('config', 'AW-374328102');
              `,
          }}
        />
      </head>
      <body className={comic.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AuthProvider>
            <TopNav />
            {children}
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
